baseurl: "/blog"
domain: ""
url: "https://lynxmic.github.io"
name: "Lynxmic Blog"
logo: "/img/wordmark.svg"
favicon: "/img/logotype.svg"
image_src: "/img/postmedia/"
rss: "feed.xml"
paginate: 30
paginate_path: "/:num/"
page_excerpts: true
timezone: Europe/Bucharest
currentyear: "2024"

author: Lynxmic
author_pic: "/img/logo.svg"
author_logo: "/img/logotype.svg"
author_gateway: "https://lynxmic.github.io"
author_youtube: "https://youtube.com/@lynxmic"
author_twitter: ""
author_fedi: "https://wetdry.world/@lynxmic"
author_discord: "https://lynxmic.github.io/discord"

source_url: "https://github.com/Lynxmic/blog"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
