baseurl: ""
domain: ""
url: "https://lynxmic.github.io"
name: "Lynxmic Blog"
logo: "/img/blog logo pink.png"
favicon: "/img/pen pink.png"
image_src: "/img/postmedia/"
rss: "/feed.xml"
paginate: 10
paginate_path: "/posts/:num/"
page_excerpts: true
timezone: Europe/Bucharest
currentyear: "2023"

author_name: "Lynxmic"
author_pic: "/img/profile.png"
author_logo: "/img/logo.png"
author_gateway: "https://linktr.ee/lynxmic"
author_youtube: "https://youtube.com/@lynxmic"
author_twitter: "https://twitter.com/lynxmic"
author_fedi: "https://wetdry.world/@lynxmic"
author_discord: "https://discord.gg/wDxDKJU2sj"

source_url: "https://github.com/Lynxmic/lynxmic.github.io"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
